# -*- coding: utf-8 -*-
"""
/***************************************************************************
 newMapView
                                 A QGIS plugin
 Abre um novo "Map View" com as camadas selecionadas.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-03-18
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Cardoso
        email                : cardoso.lara@eb.mil.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/"""
from qgis.core import *
from qgis.gui import *
from qgis.utils import iface
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtWidgets import *
from PyQt5.QtGui import *


# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .newMapView_dialog import newMapViewDialog
import os.path


class newMapView:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'newMapView_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&newMapView')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('newMapView', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/newMapView/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'newMapView'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&newMapView'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = newMapViewDialog()

        def new_theme(): #create a new theme with the selected layers
            projeto_atual=QgsProject.instance()
            layers=iface.layerTreeView().selectedLayers() #salva as camadas selecionadas (não necessariamente precisam estar checadas)
            records=[]
            for layer in layers:
                records.append(QgsMapThemeCollection.MapThemeLayerRecord(layer))
            listRecords = QgsMapThemeCollection.MapThemeRecord()
            for record in records:
                listRecords.addLayerRecord(record)
            if len(layers) == 1:
                ThemeName=layers[0].name()
            elif len(layers) > 1:
                ThemeName='Tema_Misto'
            colection_themes=projeto_atual.mapThemeCollection()
            if len(colection_themes.mapThemes())==0:
                projeto_atual.mapThemeCollection().insert(ThemeName, listRecords) #salva o novo tema como NewTheme
            else:
                ThemeName=ThemeName+str(len(colection_themes.mapThemes()))
                projeto_atual.mapThemeCollection().insert(ThemeName, listRecords) #salva o novo tema como NewTheme
            return ThemeName

        def openMapView(): #lazy method
            #abrindo o map view
            for i in range(len(iface.viewMenu().actions())):
                if iface.viewMenu().actions()[i].objectName() == 'mActionNewMapCanvas':
                    iface.viewMenu().actions()[i].trigger()
                    break
            return 0

        def trigger_theme(ThemeName,newDocks):
            qtoolBtn = newDocks[-1].findChildren(QToolButton)[4]
            qtoolBtn.showMenu()
            menuThemes = qtoolBtn.menu()
            themesActions = menuThemes.actions()
            [ ta.trigger() for ta in themesActions if ta.text() == ThemeName]
            return newDocks[-1].findChildren(QToolButton)[4]
            
        def dockWidget(): #obtem a 'localizacao' da janela aberta
            docks = []
            for widget in iface.mainWindow().children():
                if type(widget) == QDockWidget:
                    docks.append(widget)

            newDocks=[]
            for canvas in docks:
                if canvas.objectName() == 'QgsMapCanvasDockWidgetBase':
                    newDocks.append(canvas)
            return newDocks
            
        def settings(newDocks,ThemeName):
            menuSettings = newDocks[-1].findChildren(QToolButton)[5].menu() #get the menu for the next selections
            menuSettings.actions()[0].defaultWidget().children()[1].click()  #synchronize view to selection
            menuSettings.actions()[0].defaultWidget().children()[-3].setChecked(True)  #synchronize scale
            menuSettings.actions()[0].defaultWidget().children()[-1].setValue(1) # scale factor
            teste=trigger_theme(ThemeName,newDocks) #theme
            return 0
            
        ThemeName=new_theme() #create a new theme with the selected layers
        openMapView() #lazy method
        newDocks=dockWidget()
        settings(newDocks,ThemeName)